# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e9ea334ed11ed5fc3598bc4724d3bbd72a24edd0b9e2d651e9893176f5ce53c8a64b03c18055e503a2a1f3c6fa841d183432268ecca4f07f163803443af7fd44

test:
  secret_key_base: 71317537828a03e8a7b7b402461b5d5c7611a0b92cc58069d0884a8b0ee88224c3e13d89eeb6fceb60b00a25cb315df80968ca158c7bf72ad37636d0cea8461d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
